course1 = input("Please enter your favorite course: ")
mark1 = input("Enter the grade you hope to achieve for that course: ")
course2 = input("Please enter your Second favorite course: ")
mark2 = input("Enter the grade you hope to achieve for that course: ")
course3 = input("Please enter your favorite course: ")
mark3 = input("Enter the grade you hope to achieve for that course: ")
print(mark1 + " " + course1)
print(mark2 + " " + course2)
print(mark3 + " " + course3)